[package]
name = "bdi"
version = "0.1.0"
authors = ["Nima Shoghi <nimashoghi@gmail.com>"]
edition = "2018"

[lib]
name = "bdi"
path = "src/lib.rs"

[[bin]]
name = "bdi"
path = "src/main.rs"

[dependencies]
"rand" = "0.7.3"
"rayon" = "1.3.0"
"clap" = "3.0.0-beta.1"
"derive_builder" = "0.9.0"
